### PR TITLE
Add Brazilian Portuguese translation.

### PR DESCRIPTION
**Pull request by pmichelazzo**
Just a Brazilian Portuguese translation.

Thanks for the extension.

### CODE REVIEW

**Comment by tiansh** [comment]
I found out that Twitter only support "Portuguese" language without country code or writing variance. Should I simply rename this language translation to "pt" as what Twitter website do?

Screenshot of Twitter language selection

If country code must be preserved, using `pt_BR` instead of `pt-br` as the [document](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#localized_string_selection) said would be preferred (although both would work fine).

**Comment by pmichelazzo** [comment]
Hello @tiansh 

I've made the changes using the pt_BR to preserve the country code. Some fellows in PT could say "this is not Portuguese" ;)

Thanks again.

**Comment by tiansh** [comment]
Sorry for the delay. I will try to release a new version including this localization maybe during holidays next week. (As we have 7 workdays this week...)

**Comment by pmichelazzo** [comment]
No problem. Take your time.


All the best
Paulino

**Pull request merged**
